name: Run Playlist Manager

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true
  # schedule:
    # Runs every 3 hours
    # - cron: '* */8 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        WEEKLY_ID: ${{ secrets.WEEKLY_ID }}
        ARCHIVE_ID: ${{ secrets.ARCHIVE_ID }}
      run: python auth.py
